baseURL = "https://zjpsycholin.github.io/psycholinguistics/"
languageCode = "en-us"
title = "Introduction to Psycholinguistics"
theme = "archie"
copyright = "© Zhang Jun"




[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[params]
  mode = "auto"
  useCDN = false
  subtitle = ""
  katex = true

[menu]
  [[menu.main]]
    name = "Welcome"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Syllabus"
    url = "/syllabus/"
    weight = 2

  [[menu.main]]
    name = "Chapter01"
    url = "/Chapter01/"
    weight = 3

  [[menu.main]]
    name = "Chapter02 P1"
    url = "/Chapter02P1/"
    weight = 4

  [[menu.main]]
    name = "Chapter02 P2"
    url = "/Chapter02P2/"
    weight = 5

  [[menu.main]]
    name = "Chapter03 P1"
    url = "/Chapter03P1/"
    weight = 6

  [[menu.main]]
    name = "Chapter03 P2"
    url = "/Chapter03P2/"
    weight = 7

  [[menu.main]]
    name = "Chapter04 P1"
    url = "/Chapter04P1/"
    weight = 8

  [[menu.main]]
    name = "Chapter04 P2"
    url = "/Chapter04P2/"
    weight = 9

  [[menu.main]]
    name = "Chapter07"
    url = "/Chapter07/"
    weight = 10

  [[menu.main]]
    name = "Chapter08"
    url = "/Chapter08/"
    weight = 11

  [[menu.main]]
    name = "Chapter09"
    url = "/Chapter09/"
    weight = 12

  [[menu.main]]
    name = "Chapter11"
    url = "/Chapter11/"
    weight = 13

  [[menu.main]]
    name = "Chapter13"
    url = "/Chapter13/"
    weight = 14

  
